### ISSUE TITLE
High DPI sidebar scaling

### ISSUE THREAD

**Issue by AngelTomkins** [SlimeVR/SlimeVR-Docs-Site#142]
Scaling on high dpi screens extends the side bar into the centre of the screen, making the content section smaller by ratio.

Example of page at 4k resolution:
![Screenshot 2022-12-26 at 21-30-12 Configuring the Firmware Project](https://user-images.githubusercontent.com/67720650/209601985-fef52495-ab09-4774-bb0e-4fe4e4ac1b05.png)

**Comment by calliePepper** [comment]
This is intentional. 

Humans deal better with reading lots of text if the range per line is between 50-75 characters, so it is not a good idea for the content section to cover the entire screen. Since this is the case, it can either be centre aligned (as it is here) or it can be left aligned.

The benefit of having the large area of darker navigation data is it pulls the eye to the new line with a lot less mental tax than if the navigation section was thinner.
